In [1]:
import pandas as pd

In [2]:
Dietary_Interview_df = pd.read_sas('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/P_DR1IFF.XPT')

In [3]:
Dietary_Interview_df

,SEQN,WTDRD1PP,WTDR2DPP,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,DR1IM181,DR1IM201,DR1IM221,DR1IP182,DR1IP183,DR1IP184,DR1IP204,DR1IP205,DR1IP225,DR1IP226
0,109263.0,7619.483586,1.780807e+04,12.0,1.0,14.0,2.0,2.0,4.000000e+00,6.0,...,1.941000e+00,3.600000e-02,5.397605e-79,8.380000e-01,8.800000e-02,5.397605e-79,1.200000e-02,5.397605e-79,5.397605e-79,5.397605e-79
1,109263.0,7619.483586,1.780807e+04,10.0,1.0,14.0,2.0,2.0,4.000000e+00,6.0,...,1.229000e+00,1.300000e-02,5.397605e-79,5.200000e-01,1.300000e-02,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
2,109263.0,7619.483586,1.780807e+04,4.0,1.0,14.0,2.0,2.0,4.000000e+00,6.0,...,5.683000e+00,8.800000e-02,5.000000e-03,3.482000e+00,4.210000e-01,5.000000e-03,2.900000e-02,1.000000e-02,1.000000e-02,5.397605e-79
3,109263.0,7619.483586,1.780807e+04,9.0,1.0,14.0,2.0,2.0,4.000000e+00,6.0,...,1.000000e-02,5.397605e-79,5.397605e-79,6.900000e-02,1.500000e-02,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
4,109263.0,7619.483586,1.780807e+04,13.0,1.0,14.0,2.0,2.0,4.000000e+00,6.0,...,2.382000e+00,1.400000e-02,5.397605e-79,1.209000e+00,1.140000e-01,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183905,124821.0,3043.724330,5.397605e-79,5.0,1.0,81.0,2.0,1.0,5.397605e-79,7.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
183906,124821.0,3043.724330,5.397605e-79,4.0,1.0,81.0,2.0,1.0,5.397605e-79,7.0,...,1.600000e+00,5.397605e-79,2.000000e-03,2.632000e+00,2.010000e-01,5.397605e-79,1.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79
183907,124821.0,3043.724330,5.397605e-79,3.0,1.0,81.0,2.0,1.0,5.397605e-79,7.0,...,3.900000e-01,4.000000e-03,5.397605e-79,6.530000e-01,7.900000e-02,5.397605e-79,9.000000e-03,1.500000e-02,1.000000e-03,1.600000e-02
183908,124821.0,3043.724330,5.397605e-79,2.0,1.0,81.0,2.0,1.0,5.397605e-79,7.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
183909,124821.0,3043.724330,5.397605e-79,1.0,1.0,81.0,2.0,1.0,5.397605e-79,7.0,...,2.018700e+01,4.820000e-01,1.800000e-02,1.074500e+01,1.281000e+00,9.000000e-03,2.480000e-01,9.600000e-02,8.300000e-02,3.210000e-01

In [2]:
Dietary_Interview_df2 = pd.read_sas('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/P_DR2IFF.XPT')

In [4]:
Dietary_Interview_df.describe()

,SEQN,WTDRD1PP,WTDR2DPP,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,DR1IM181,DR1IM201,DR1IM221,DR1IP182,DR1IP183,DR1IP184,DR1IP204,DR1IP205,DR1IP225,DR1IP226
count,183910.000000,183910.000000,1.839100e+05,183910.000000,183910.000000,183910.000000,183910.000000,183910.000000,174783.000000,183910.000000,...,1.825060e+05,1.825060e+05,1.825060e+05,1.825060e+05,1.825060e+05,1.825060e+05,1.825060e+05,1.825060e+05,1.825060e+05,1.825060e+05
mean,117091.688141,26936.526968,2.727404e+04,9.003192,1.047436,72.913876,1.984134,1.864048,12.204293,4.528025,...,1.756106e+00,2.114459e-02,2.020125e-03,1.150229e+00,1.163193e-01,5.808521e-04,9.210919e-03,2.119382e-03,1.735143e-03,3.710645e-03
std,4495.637420,36197.685279,4.368438e+04,6.056732,0.374245,21.422692,0.124959,0.342739,12.938323,2.195818,...,3.494626e+00,6.504972e-02,2.593395e-02,2.607304e+00,3.075174e-01,7.697789e-03,2.942947e-02,3.210288e-02,1.412127e-02,4.926647e-02
min,109263.000000,805.552485,5.397605e-79,1.000000,1.000000,14.000000,1.000000,1.000000,-42.000000,1.000000,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
25%,113215.000000,8030.148191,5.317873e+03,4.000000,1.000000,73.000000,2.000000,2.000000,3.000000,2.000000,...,5.397605e-79,5.397605e-79,5.397605e-79,2.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
50%,117143.000000,15105.403495,1.342615e+04,8.000000,1.000000,81.000000,2.000000,2.000000,10.000000,5.000000,...,2.360000e-01,5.397605e-79,5.397605e-79,1.120000e-01,1.600000e-02,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
75%,120978.000000,30874.730753,3.139270e+04,13.000000,1.000000,86.000000,2.000000,2.000000,19.000000,6.000000,...,2.104000e+00,1.700000e-02,5.397605e-79,1.168000e+00,1.000000e-01,5.397605e-79,4.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79
max,124821.000000,538404.429708,7.029436e+05,46.000000,4.000000,94.000000,2.000000,2.000000,91.000000,7.000000,...,9.982000e+01,4.925000e+00,6.974000e+00,1.545150e+02,1.634400e+01,5.800000e-01,1.433000e+00,3.704000e+00,1.642000e+00,4.872000e+00

In [5]:
Dietary_Interview_df.to_csv('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/P_DR1IFF.csv')

In [3]:
Dietary_Interview_df2.to_csv('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/P_DR2IFF.csv')

In [3]:
Reproductive_Health_df = pd.read_sas('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/P_RHQ.XPT')

In [4]:
Reproductive_Health_df.describe()

,SEQN,RHQ010,RHD018,RHQ020,RHQ031,RHD043,RHQ060,RHQ070,RHQ074,RHQ076,...,RHD280,RHQ305,RHQ332,RHQ540,RHQ542A,RHQ542B,RHQ542C,RHQ542D,RHQ554,RHQ570
count,5314.000000,4.932000e+03,732.000000,50.00000,4870.000000,2275.000000,2300.000000,94.000000,2836.000000,2836.000000,...,4037.000000,4036.000000,471.000000,4054.000000,517.000000,87.0,171.0,11.0,512.000000,512.000000
mean,117038.059089,2.299128e+01,781.215847,4.08000,1.480903,6.041319,85.410870,28.829787,1.903385,1.933004,...,1.788952,1.971754,57.828025,1.870745,10.860735,11.0,12.0,13.0,1.859375,2.505859
std,4488.643083,1.011786e+02,2416.213595,2.50583,0.550905,5.911771,192.499831,41.330724,0.398200,0.321631,...,0.513492,0.857474,116.098757,0.631102,8.718462,0.0,0.0,0.0,2.148077,2.146304
min,109264.000000,5.397605e-79,103.000000,1.00000,1.000000,1.000000,19.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,19.000000,1.000000,10.000000,11.0,12.0,13.0,1.000000,1.000000
25%,113162.250000,1.100000e+01,139.000000,2.25000,1.000000,3.000000,40.000000,4.000000,2.000000,2.000000,...,2.000000,2.000000,37.000000,2.000000,10.000000,11.0,12.0,13.0,1.000000,2.000000
50%,117056.000000,1.200000e+01,150.000000,3.00000,1.000000,7.000000,47.000000,6.000000,2.000000,2.000000,...,2.000000,2.000000,45.000000,2.000000,10.000000,11.0,12.0,13.0,1.000000,2.000000
75%,120924.750000,1.400000e+01,162.000000,4.00000,2.000000,7.000000,52.000000,76.000000,2.000000,2.000000,...,2.000000,2.000000,50.000000,2.000000,10.000000,11.0,12.0,13.0,2.000000,2.000000
max,124817.000000,9.990000e+02,9999.000000,9.00000,9.000000,99.000000,999.000000,99.000000,9.000000,9.000000,...,9.000000,9.000000,999.000000,9.000000,99.000000,11.0,12.0,13.0,9.000000,9.000000

In [5]:
Reproductive_Health_df.to_csv('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/P_RHQ.csv')

In [5]:
df = pd.merge(Dietary_Interview_df, Reproductive_Health_df, how='inner', on = 'SEQN')

In [6]:
df.describe()

,SEQN,WTDRD1PP,WTDR2DPP,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,RHD280,RHQ305,RHQ332,RHQ540,RHQ542A,RHQ542B,RHQ542C,RHQ542D,RHQ554,RHQ570
count,71949.000000,71949.000000,7.194900e+04,71949.000000,71949.0,71949.000000,71949.0,71949.000000,68461.000000,71949.000000,...,59594.000000,59594.000000,7230.000000,59835.000000,8257.000000,1407.0,2973.0,178.0,8166.000000,8166.000000
mean,117079.250358,30630.925515,3.125716e+04,9.291373,1.0,72.560856,2.0,1.882500,11.912622,4.532572,...,1.777360,1.964191,54.466390,1.846912,10.980865,11.0,12.0,13.0,1.863948,2.524492
std,4472.675436,39063.977341,4.751223e+04,6.293172,0.0,21.763369,0.0,0.322017,12.896280,2.179819,...,0.487764,0.847723,99.079414,0.606696,9.292218,0.0,0.0,0.0,2.142271,2.190180
min,109264.000000,1551.658449,5.397605e-79,1.000000,1.0,14.000000,2.0,1.000000,-37.000000,1.000000,...,1.000000,1.000000,19.000000,1.000000,10.000000,11.0,12.0,13.0,1.000000,1.000000
25%,113257.000000,9367.487213,6.608144e+03,4.000000,1.0,73.000000,2.0,2.000000,3.000000,3.000000,...,2.000000,2.000000,38.000000,2.000000,10.000000,11.0,12.0,13.0,1.000000,2.000000
50%,117105.000000,17415.112298,1.603896e+04,8.000000,1.0,81.000000,2.0,2.000000,9.000000,5.000000,...,2.000000,2.000000,45.000000,2.000000,10.000000,11.0,12.0,13.0,1.000000,2.000000
75%,120931.000000,35237.600842,3.719980e+04,13.000000,1.0,86.000000,2.0,2.000000,19.000000,6.000000,...,2.000000,2.000000,51.000000,2.000000,10.000000,11.0,12.0,13.0,2.000000,2.000000
max,124817.000000,538404.429708,7.029436e+05,46.000000,1.0,94.000000,2.0,2.000000,91.000000,7.000000,...,9.000000,9.000000,999.000000,9.000000,99.000000,11.0,12.0,13.0,9.000000,9.000000

In [7]:
df['RHD143'].value_counts()

2.0    13982
1.0     1005
9.0      231
Name: RHD143, dtype: int64

In [8]:
RHD143_df = df[df['RHD143']== 1.0]

In [9]:
RHD143_df.describe()

,SEQN,WTDRD1PP,WTDR2DPP,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,RHD280,RHQ305,RHQ332,RHQ540,RHQ542A,RHQ542B,RHQ542C,RHQ542D,RHQ554,RHQ570
count,1005.000000,1005.000000,1.005000e+03,1005.000000,1005.0,1005.000000,1005.0,1005.000000,9.620000e+02,1005.000000,...,1005.0,1005.0,0.0,1005.000000,15.0,0.0,14.0,0.0,15.0,15.0
mean,117738.238806,29676.796425,3.152491e+04,9.539303,1.0,73.165174,2.0,1.848756,9.883576e+00,5.049751,...,2.0,2.0,NaN,1.971144,10.0,NaN,12.0,NaN,2.0,2.0
std,4350.648096,26868.132806,3.829596e+04,6.283928,0.0,21.093856,0.0,0.358465,1.403693e+01,2.105181,...,0.0,0.0,NaN,0.167484,0.0,NaN,0.0,NaN,0.0,0.0
min,109447.000000,1799.980997,5.397605e-79,1.000000,1.0,14.000000,2.0,1.000000,-2.900000e+01,1.000000,...,2.0,2.0,NaN,1.000000,10.0,NaN,12.0,NaN,2.0,2.0
25%,113830.000000,10712.248557,5.930629e+03,4.000000,1.0,73.000000,2.0,2.000000,5.397605e-79,4.000000,...,2.0,2.0,NaN,2.000000,10.0,NaN,12.0,NaN,2.0,2.0
50%,117595.000000,20337.343422,1.720451e+04,9.000000,1.0,81.000000,2.0,2.000000,6.000000e+00,6.000000,...,2.0,2.0,NaN,2.000000,10.0,NaN,12.0,NaN,2.0,2.0
75%,121924.000000,41066.068922,4.157837e+04,13.000000,1.0,88.000000,2.0,2.000000,2.000000e+01,7.000000,...,2.0,2.0,NaN,2.000000,10.0,NaN,12.0,NaN,2.0,2.0
max,124780.000000,141338.343374,1.908676e+05,31.000000,1.0,91.000000,2.0,2.000000,4.200000e+01,7.000000,...,2.0,2.0,NaN,2.000000,10.0,NaN,12.0,NaN,2.0,2.0

In [17]:
RHD143_df.to_csv('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/RHD143.csv')

In [10]:
RHQ076_df = df[(df['RHQ076']== 1.0)]

In [11]:
RHQ076_df.describe()

,SEQN,WTDRD1PP,WTDR2DPP,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,RHD280,RHQ305,RHQ332,RHQ540,RHQ542A,RHQ542B,RHQ542C,RHQ542D,RHQ554,RHQ570
count,3124.000000,3124.000000,3.124000e+03,3124.000000,3124.0,3124.000000,3124.0,3124.000000,2964.000000,3124.000000,...,3101.000000,3101.000000,103.000000,3124.000000,278.0,13.0,95.0,52.0,278.000000,278.000000
mean,116881.896607,37400.870327,4.359945e+04,9.670615,1.0,72.341229,2.0,1.915493,11.213225,5.013124,...,1.921316,1.966785,38.766990,1.905570,10.0,11.0,12.0,13.0,1.618705,1.931655
std,4427.073909,44181.473528,5.915731e+04,6.294971,0.0,21.579395,0.0,0.278191,13.582329,2.090834,...,0.269289,0.179227,6.526273,0.548378,0.0,0.0,0.0,0.0,0.486581,0.252793
min,109291.000000,1727.251573,5.397605e-79,1.000000,1.0,14.000000,2.0,1.000000,-34.000000,1.000000,...,1.000000,1.000000,31.000000,1.000000,10.0,11.0,12.0,13.0,1.000000,1.000000
25%,113109.000000,12504.240914,1.096138e+04,5.000000,1.0,73.000000,2.0,2.000000,3.000000,4.000000,...,2.000000,2.000000,35.000000,2.000000,10.0,11.0,12.0,13.0,1.000000,2.000000
50%,116706.000000,20981.742096,2.183537e+04,9.000000,1.0,81.000000,2.0,2.000000,7.000000,6.000000,...,2.000000,2.000000,37.000000,2.000000,10.0,11.0,12.0,13.0,2.000000,2.000000
75%,120519.000000,43246.720318,4.649075e+04,14.000000,1.0,86.000000,2.0,2.000000,17.000000,7.000000,...,2.000000,2.000000,45.000000,2.000000,10.0,11.0,12.0,13.0,2.000000,2.000000
max,124813.000000,253485.315766,3.309517e+05,32.000000,1.0,91.000000,2.0,2.000000,58.000000,7.000000,...,2.000000,2.000000,52.000000,9.000000,10.0,11.0,12.0,13.0,2.000000,2.000000

In [14]:
RHQ076_df

,SEQN,WTDRD1PP,WTDR2DPP,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,RHD280,RHQ305,RHQ332,RHQ540,RHQ542A,RHQ542B,RHQ542C,RHQ542D,RHQ554,RHQ570
110,109291.0,12733.439510,27963.088586,4.0,1.0,49.0,2.0,2.0,6.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
111,109291.0,12733.439510,27963.088586,14.0,1.0,49.0,2.0,2.0,6.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
112,109291.0,12733.439510,27963.088586,15.0,1.0,49.0,2.0,2.0,6.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
113,109291.0,12733.439510,27963.088586,3.0,1.0,49.0,2.0,2.0,6.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
114,109291.0,12733.439510,27963.088586,9.0,1.0,49.0,2.0,2.0,6.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71935,124813.0,7457.881926,5816.929324,5.0,1.0,90.0,2.0,2.0,NaN,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71936,124813.0,7457.881926,5816.929324,4.0,1.0,90.0,2.0,2.0,NaN,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71937,124813.0,7457.881926,5816.929324,3.0,1.0,90.0,2.0,2.0,NaN,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71938,124813.0,7457.881926,5816.929324,2.0,1.0,90.0,2.0,2.0,NaN,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71939,124813.0,7457.881926,5816.929324,1.0,1.0,90.0,2.0,2.0,NaN,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
RHD143_df

,SEQN,WTDRD1PP,WTDR2DPP,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,RHD280,RHQ305,RHQ332,RHQ540,RHQ542A,RHQ542B,RHQ542C,RHQ542D,RHQ554,RHQ570
889,109447.0,33026.862559,28231.480109,9.0,1.0,88.0,2.0,2.0,29.0,7.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
890,109447.0,33026.862559,28231.480109,1.0,1.0,88.0,2.0,2.0,29.0,7.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
891,109447.0,33026.862559,28231.480109,2.0,1.0,88.0,2.0,2.0,29.0,7.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
892,109447.0,33026.862559,28231.480109,6.0,1.0,88.0,2.0,2.0,29.0,7.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
893,109447.0,33026.862559,28231.480109,16.0,1.0,88.0,2.0,2.0,29.0,7.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71722,124780.0,19937.540621,17042.680953,5.0,1.0,14.0,2.0,2.0,16.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71723,124780.0,19937.540621,17042.680953,4.0,1.0,14.0,2.0,2.0,16.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71724,124780.0,19937.540621,17042.680953,3.0,1.0,14.0,2.0,2.0,16.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71725,124780.0,19937.540621,17042.680953,2.0,1.0,14.0,2.0,2.0,16.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71726,124780.0,19937.540621,17042.680953,1.0,1.0,14.0,2.0,2.0,16.0,6.0,...,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
RHQ076_df.to_csv('/Users/soumyadeepray/Documents/Research_Project-Nutrition_Sciences/NHANES/data/RHQ076.csv')

In [12]:
n = len(pd.unique(RHD143_df['SEQN']))
print("No.of.unique values :", n)

No.of.unique values : 64

In [13]:
n = len(pd.unique(RHQ076_df['SEQN']))
print("No.of.unique values :", n)

No.of.unique values : 195

In [17]:
RHD143_df_transposed = RHD143_df.T
RHD143_df_transposed

,889,890,891,892,893,894,895,896,897,898,...,71717,71718,71719,71720,71721,71722,71723,71724,71725,71726
SEQN,109447.000000,109447.000000,109447.000000,109447.000000,109447.000000,109447.000000,109447.000000,109447.000000,109447.000000,109447.000000,...,124780.000000,124780.000000,124780.000000,124780.000000,124780.000000,124780.000000,124780.000000,124780.000000,124780.000000,124780.000000
WTDRD1PP,33026.862559,33026.862559,33026.862559,33026.862559,33026.862559,33026.862559,33026.862559,33026.862559,33026.862559,33026.862559,...,19937.540621,19937.540621,19937.540621,19937.540621,19937.540621,19937.540621,19937.540621,19937.540621,19937.540621,19937.540621
WTDR2DPP,28231.480109,28231.480109,28231.480109,28231.480109,28231.480109,28231.480109,28231.480109,28231.480109,28231.480109,28231.480109,...,17042.680953,17042.680953,17042.680953,17042.680953,17042.680953,17042.680953,17042.680953,17042.680953,17042.680953,17042.680953
DR1ILINE,9.000000,1.000000,2.000000,6.000000,16.000000,12.000000,11.000000,13.000000,14.000000,3.000000,...,10.000000,9.000000,8.000000,7.000000,6.000000,5.000000,4.000000,3.000000,2.000000,1.000000
DR1DRSTZ,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RHQ542B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RHQ542C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RHQ542D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RHQ554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RHQ570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN